### ISSUE TITLE
Consider making authentication entries smaller

### ISSUE THREAD

**Issue by x80486** [standardnotes/token-vault#20]
Right now, authentication entries uses the entire width of the container. There is a lot of space that's not used for anything, so I think it would be better to make them smaller – but still responsive.

**Comment by prcmt** [comment]
I don't mind the horizontal space, but I'd love to have the entries be shorter. You don't need to have many entries before you're always scrolling to find them, and since they're not in any particular order you can't efficiently find the one you're looking for.

At the moment entries are about two thirds whitespace vertically.

**Comment by JaspalSuri** [comment]
Hi, thank you for the feedback! I'll pass it along to the team for review.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah, would be great if you could reduce the vertical spacing 👍

**Comment by prcmt** [comment]
It would appear to be as simple as changing the padding on [this line](https://github.com/sn-extensions/token-vault/blob/master/app/stylesheets/main.scss#L80).

**Comment by mobitar** [comment]
How many entries do you all have, roughly?

**Comment by prcmt** [comment]
> How many entries do you all have, roughly?

~25

**Comment by h0jeZvgoxFepBQ2C** [comment]
2 seperate Notes, one with 15 and the other one with about 25.

**Comment by mobitar** [comment]
Wow, quite a lot of services! Indeed, I can see how the current arrangement can be fatiguing. It's not as simple as a padding change since we have to account for different configurations and presence of fields, but we'll keep this in mind as we explore a sort of v2 upgrade. The main features we'll want for that is some sort of drag and drop sorting, and also auto sorting based on name.

**Comment by h0jeZvgoxFepBQ2C** [comment]
And pleeeease this: https://github.com/sn-extensions/token-vault/issues/26 - it would also help drastically to find items much faster.

**Comment by saizai** [comment]
Second this. I only have 14, but still. Especially on mobile, lots of wasted vertical space.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would still be nice to get implemented now that version 2 is out now?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Any updates about this?
